[package]
name = "Network-Addon-Installer"
version = "0.1.0"
authors = ["durfsurn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
