trigger:
  tags:
    include:
      - v*
    
pool:
  vmImage: 'ubuntu-latest'

jobs: 
- job:
  displayName: 'Build Elm into Javascript'
  steps:
  - task: Bash@3
    displayName: 'Clone submodule'
    env: 
      PASSWORD: $(PASSWORD)
    inputs:
      targetType: 'inline'
      script: 'git clone https://durfsurn:$(PASSWORD)@github.com/Durfsurn/Installer-Assets.git installation'
  
  - task: Bash@3
    displayName: 'Build Elm'
    inputs:
      targetType: 'inline'
      script: |
          chmod +x elm_compile_opt.sh
          ./elm_compile_opt.sh

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'static'
      Contents: 'main.js'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Elm'
      publishLocation: 'Container'
