trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs: 
- job:
  displayName: 'Build NAM Installer for 64bit Linux'
  steps:
  - task: Bash@3
    displayName: 'Set Toolchain'
    inputs:
      targetType: 'inline'
      script: 'rustup default stable-x86_64-unknown-linux-gnu'

  - task: Bash@3
    displayName: 'Build Installer'
    inputs:
      targetType: 'inline'
      script: 'cargo build --release'
  - task: Bash@3
    displayName: 'View Installer Folder'
    inputs:
      targetType: 'inline'
      script: 'ls -la target/release'
- job:
  displayName: 'Build NAM Installer for 32bit Linux'
  steps:
  - task: Bash@3
    displayName: 'Set Toolchain'
    inputs:
      targetType: 'inline'
      script: 'rustup default stable-i686-unknown-linux-gnu'

  - task: Bash@3
    displayName: 'Build Installer'
    inputs:
      targetType: 'inline'
      script: 'cargo build --release'
  - task: Bash@3
    displayName: 'View Installer Folder'
    inputs:
      targetType: 'inline'
      script: 'ls -la target/release'