trigger:
  - master
  
pool:
  vmImage: 'macOS-latest'

jobs:
- job:
  displayName: 'Build NAM Installer for 64bit Mac'
  steps:
  - task: Bash@3
    displayName: 'Clone submodule'
    inputs:
      targetType: 'inline'
      script: 'git clone https://github.com/Durfsurn/Installer-Assets.git installation'

  - task: Bash@3
    displayName: 'Set Toolchain'
    inputs:
      targetType: 'inline'
      script: 'rustup default stable-x86_64-apple-darwin'

  - task: Bash@3
    displayName: 'Build Elm'
    inputs:
      targetType: 'inline'
      script: './elm_compile.sh'
    
  - task: Bash@3
    displayName: 'Build Installer'
    inputs:
      targetType: 'inline'
      script: 'cargo build --release'
  - task: Bash@3
    displayName: 'View Installer Folder'
    inputs:
      targetType: 'inline'
      script: 'ls -la target/release'