# trigger:
#   - master
  
pool:
  vmImage: 'windows-latest'

jobs: 
- job:
  timeoutInMinutes: 360
  displayName: 'Build NAM Installer for 64bit Windows'
  steps:
  - task: Bash@3
    displayName: 'Clone submodule'
    env: 
      PASSWORD: $(PASSWORD)
    inputs:
      targetType: 'inline'
      script: 'git clone https://durfsurn:$(PASSWORD)@github.com/Durfsurn/Installer-Assets.git installation'
      
  - task: Cache@2
    displayName: Cache target 
    inputs:
      key: 'win64-target | "$(Agent.OS)" | $(System.DefaultWorkingDirectory)/Cargo.lock'
      path: $(System.DefaultWorkingDirectory)/target
      
  - task: DownloadBuildArtifacts@0
    displayName: 'Download main.js'
    inputs:
      buildType: 'specific'
      project: 'eabaa3ca-a386-4633-b183-c4f2ac1c2667'
      pipeline: '7'
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'Elm'
      itemPattern: 'Elm/main.js'
      downloadPath: '$(System.DefaultWorkingDirectory)/static/'
    
  - task: Bash@3
    displayName: 'Move main.js'
    inputs:
      targetType: 'inline'
      script: 'mv static/Elm/main.js static/main.js'

  - task: Bash@3
    displayName: 'Set Toolchain'
    inputs:
      targetType: 'inline'
      script: 'rustup default stable-x86_64-pc-windows-msvc'

  - task: Bash@3
    displayName: 'Build Installer'
    inputs:
      targetType: 'inline'
      script: 'cargo build --release'

  - task: Bash@3
    displayName: 'View Installer Folder'
    inputs:
      targetType: 'inline'
      script: 'ls -la target/release'

  - task: Bash@3
    displayName: 'Test'
    inputs:
      targetType: 'inline'
      script: 'ls -la'
      
  - task: Bash@3
    displayName: 'Embed .ico'
    inputs:
      targetType: 'inline'
      script: '$(System.DefaultWorkingDirectory)/rcedit "target/release/network-addon-installer.exe" --set-icon "static/favicon.ico"'

  - task: Bash@3
    displayName: 'Rename executable'
    inputs:
      targetType: 'inline'
      script: 'mv "target/release/network-addon-installer.exe" "target/release/network-addon-installer-win64.exe"'
  
  - task: CopyFiles@2
    displayName: 'Copy executable to staging directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/target/release'
      Contents: 'network-addon-installer-win64.exe'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Windows'
      publishLocation: 'Container'

- job:
  timeoutInMinutes: 360
  displayName: 'Build NAM Installer for 32bit Windows'
  steps:
  - task: Cache@2
    displayName: Cache target 
    inputs:
      key: 'win32target | "$(Agent.OS)" | $(System.DefaultWorkingDirectory)/Cargo.lock'
      path: $(System.DefaultWorkingDirectory)/target

  - task: Bash@3
    displayName: 'Clone submodule'
    env: 
      PASSWORD: $(PASSWORD)
    inputs:
      targetType: 'inline'
      script: 'git clone https://durfsurn:$(PASSWORD)@github.com/Durfsurn/Installer-Assets.git installation'
      
  - task: Bash@3
    displayName: 'Remove 64bit NAM folders'
    inputs:
      targetType: 'inline'
      script: |
        ls -la installation
        rm -rf installation/\$2\=z_NAM\ Controller_RHD_4GB_Full/
        rm -rf installation/\$3+z_NAM\ Controller_LHD_4GB_Full/
        rm -rf installation/2\ Additional\ Network\ Features/RealHighway/
        ls -la installation
        ls -la installation/2\ Additional\ Network\ Features

  - task: ArchiveFiles@2
    displayName: 'Create Zip Archive'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/installation'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(System.DefaultWorkingDirectory)/installation.zip'
      replaceExistingArchive: true

  - task: Bash@3
    displayName: 'Check zip size'
    inputs:
      targetType: 'inline'
      script: |
        du -h installation.zip 
        mv installation.zip data.bin
        
  - task: Bash@3
    displayName: 'Set Toolchain'
    inputs:
      targetType: 'inline'
      script: 'rustup default stable-i686-pc-windows-msvc'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download main.js'
    inputs:
      buildType: 'specific'
      project: 'eabaa3ca-a386-4633-b183-c4f2ac1c2667'
      pipeline: '7'
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'Elm'
      itemPattern: 'Elm/main.js'
      downloadPath: '$(System.DefaultWorkingDirectory)/static/'
    
  - task: Bash@3
    displayName: 'Move main.js'
    inputs:
      targetType: 'inline'
      script: 'mv static/Elm/main.js static/main.js'

  - task: Bash@3
    displayName: 'Build Installer'
    inputs:
      targetType: 'inline'
      script: 'cargo build --release'

  - task: Bash@3
    displayName: 'View Installer Folder'
    inputs:
      targetType: 'inline'
      script: 'ls -la target/release'

  - task: Bash@3
    displayName: 'Embed .ico'
    inputs:
      targetType: 'inline'
      script: '$(System.DefaultWorkingDirectory)/rcedit "target/release/network-addon-installer.exe" --set-icon "static/favicon.ico"'

  - task: Bash@3
    displayName: 'Rename executable'
    inputs:
      targetType: 'inline'
      script: 'mv "target/release/network-addon-installer.exe" "target/release/network-addon-installer-win32.exe"'
  
  - task: Bash@3
    displayName: 'Test'
    inputs:
      targetType: 'inline'
      script: 'ls -la'
  
  - task: CopyFiles@2
    displayName: 'Copy executable to staging directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/target/release'
      Contents: 'network-addon-installer-win32.exe'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: CopyFiles@2
    displayName: 'Copy files to staging directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/installation'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Windows'
      publishLocation: 'Container'