# trigger:
#   - master
  
pool:
  vmImage: 'windows-latest'

jobs: 
- job:
  displayName: 'Build NAM Installer for 64bit Windows'
  steps:
  - task: Bash@3
    displayName: 'Clone submodule'
    inputs:
      targetType: 'inline'
      script: 'git clone https://github.com/Durfsurn/Installer-Assets.git installation'
      
  - task: DownloadBuildArtifacts@0
    displayName: 'Download main.js'
    inputs:
      buildType: 'specific'
      project: 'eabaa3ca-a386-4633-b183-c4f2ac1c2667'
      pipeline: '7'
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'Elm'
      itemPattern: 'main.js'
      downloadPath: '$(System.DefaultWorkingDirectory)/static/'
    
  - task: Bash@3
    displayName: 'Build Installer'
    inputs:
      targetType: 'inline'
      script: 'ls -la static'

  - task: Bash@3
    displayName: 'Set Toolchain'
    inputs:
      targetType: 'inline'
      script: 'rustup default stable-x86_64-pc-windows-gnu'

  - task: Bash@3
    displayName: 'Build Installer'
    inputs:
      targetType: 'inline'
      script: 'cargo build --release'

  - task: Bash@3
    displayName: 'View Installer Folder'
    inputs:
      targetType: 'inline'
      script: 'ls -la target/release'

- job:
  displayName: 'Build NAM Installer for 32bit Windows'
  steps:
  - task: Bash@3
    displayName: 'Clone submodule'
    inputs:
      targetType: 'inline'
      script: 'git clone https://github.com/Durfsurn/Installer-Assets.git installation'

  - task: Bash@3
    displayName: 'Set Toolchain'
    inputs:
      targetType: 'inline'
      script: 'rustup default stable-i686-pc-windows-msvc'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download main.js'
    inputs:
      buildType: 'specific'
      project: 'eabaa3ca-a386-4633-b183-c4f2ac1c2667'
      pipeline: '7'
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'Elm'
      itemPattern: 'main.js'
      downloadPath: '$(System.DefaultWorkingDirectory)/static/'
    
  - task: Bash@3
    displayName: 'Build Installer'
    inputs:
      targetType: 'inline'
      script: 'ls -la static'

  - task: Bash@3
    displayName: 'Build Installer'
    inputs:
      targetType: 'inline'
      script: 'cargo build --release'

  - task: Bash@3
    displayName: 'View Installer Folder'
    inputs:
      targetType: 'inline'
      script: 'ls -la target/release'